version: "3.2"
services:
    nginx:
      image: nginx
      restart: always
      volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./app:/usr/share/nginx/html
      ports:
        - "80:80"

    php:
      build: ./docker/php
      restart: always
      expose:
        - "9000"
      volumes:
        - ./app:/usr/share/nginx/html

    mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test

